### ISSUE TITLE
Tag field seems to be deprecated in the example

### ISSUE THREAD

**Issue by jaudiger** [getporter/docker-compose-mixin#17]
Hi,

Just a small remark about the example, it seems the field `tag` has been deprecated in favor of field `registry`. This is what I got when I did a `porter build`:

```log
WARNING: the tag field has been deprecated; please replace with a value for the registry field on the Porter manifest instead
```

The line is here: https://github.com/getporter/docker-compose-mixin/blob/main/examples/compose/porter.yaml#L13

**Comment by vdice** [comment]
Thanks for the issue!  I've issued a PR to address this: https://github.com/getporter/docker-compose-mixin/pull/19

**Comment by jaudiger** [comment]
Thanks :+1:
